### ISSUE TITLE
Tasks' monitoring

### ISSUE THREAD

**Issue by rmhere** [MarcinPieczka/Mongo-BTC-Blocks-Database#12]
Add to the project's webserver the capability of showing the tasks: submitted, finished, computing, error. If possible, include the possibility of looking at the ranges of dates.

**Comment by rmhere** [comment]
If possible, this can be added to the main web component of the project

**Comment by MarcinPieczka** [comment]
@rmhere I've added a functionality to do all of these things in admin page, please check if that fits your needs

**Comment by MarcinPieczka** [comment]
Done in admin
