### ISSUE TITLE
Handle negative values in URLconf

### ISSUE THREAD

**Issue by rmhere** [MarcinPieczka/Mongo-BTC-Blocks-Database#22]
Django does not handle negative values submitted as params correctly:
get_blocks_number/0/-1 returns an error of not finding proper endpoint

**Comment by MarcinPieczka** [comment]
@rmhere as we spoke previously, can we close this issu as "Won't do" ?

**Comment by rmhere** [comment]
Yes, the endpoint will be modified and negative values will be simply recalculated before calling the endpoint.
