### ISSUE TITLE
Create mailing system

### ISSUE THREAD

**Issue by MarcinPieczka** [MarcinPieczka/Mongo-BTC-Blocks-Database#8]

**Comment by MarcinPieczka** [comment]
- place in UI to input your email and verify it
- keep only a hash of email in db
- optional email param in every query
- sender dru@bergplace.org
- reply to dru-support@bergplace.org

**Comment by MarcinPieczka** [comment]
Remove email from db after task has succeeded

**Comment by MarcinPieczka** [comment]
USE CASE

EMAIL REGISTRATION

usual line:
- register email
- get info that email have been sent
- click link in email
- get info that email is verified

already sent but not yet verified line:
- register email
- get info that email was already sent so we're resending
- click link in email
- get info that email is verified

already verified line:
- register email
- info that email is already verified

invalid email address line:
- register email
- info that email is invalid

RUN TASK WITH EMAIL

usual line:
- send task request with email field
- executes task and sends email on each status change
- attaches result to last email?

email not verified/ not registered line:
- send task request with email field
- get error that email is not verified/ not registered

email verified but can't send email for some reason line:
- send task request with email field
- proceed with running the task without sending an email or let's fail the task?

**Comment by MarcinPieczka** [comment]
The easiest, least hack'y solution to enable users to get notifications about tasks via email would be to create separate api. It would look like this:

GET www.out-app.org/api/someapi/
result of above request would get you url to get the result so if you want to get notifications via email what would you need to do is
POST the-url-you-get-in-previous-request WITH DATA {email: myemail@email.com}

This is both easiest to implement and would reduce confusion with api calls, because if you have api call via GET method, you would have two versions of the same api, one without email as param, and one with email. And if you would have api via POST method, you'd need to use email param, so that seams more complicated

What do you think @rmhere ?

**Comment by rmhere** [comment]
Am I thinking correctly that the latter POST call will impose the e-mail registration procedure, too? Of course, assuming that the email is not registered yet. This seems fairly OK and, after a second thought, even better, since multiple people can send POSTs regarding the same query to be notified separately, if I am not wrong.

**Comment by MarcinPieczka** [comment]
done
